### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by matthewfbenjamin** [remedyhealth/contentfaux#17]
When I run my tests, I am getting an AssertionError whenever I do not unstub before running the single test. If I were to uncomment the `Contentfaux.unstub()` seen below, the test will pass but none of the mocked data is used.

```
  describe('fetchAuthors()', () => {
    // Contentfaux.unstub()
    it('should kick off two actions', () => {
      const store = mockStore({
        isSending: false,
        authors: {},
        ui: { error: '' },
      })
      return store.dispatch(actions.fetchAuthors())
        .then(() => {
          const response = store.getActions()
          cExpect(response).to.have.lengthOf(2)
          cExpect(response[0]).to.deep.equal(expectedActions[0])
        })
    })
  })

```

**Comment by mrsteele** [comment]
Hey @mbenjamin618!

Sorry to hear you are having some problems. I will be glad to take a look at some of this stuff with you. Is your code public by any chance?

First, I imagine you have already stubbed your data? After installing `contentfaux` you can create a script like so:
```
{
  "scripts": {
    "stub": "contentfaux setup"
  }
}
```

As long as everything is configured properly with the data from your space, you can get all that data stubbed out.

After that, you can simple import/require cuntentfaux and it instantly stubs your data.

If you need your test to actually interface with contentfaux, you can use `contentfaux.unstub()` and that essentially "disables" contentfaux momentarily. Of course if you need it restubbed you can call `contentfaux.stub()` and you are back in business.

Please let me know if anything I have suggested above has helped, otherwise let me know how else I can help you out.

**Comment by matthewfbenjamin** [comment]
@mrsteele thanks for the response, but my issue is that in the file that I'm using contentfaux I am getting an error:

```
AssertionError [ERR_ASSERTION]: false == true
    at socketOnData (_http_server.js:440:3)
    at emitOne (events.js:121:20)
    at TlsSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TlsSocket.Readable.push (_stream_readable.js:208:10)
    at InternalSocket.onread (net.js:594:20)
    at InternalSocket.readData (~/node_modules/mitm/lib/internal_socket.js:43:13)
    at emitOne (events.js:116:13)
    at InternalSocket.emit (events.js:211:7)
npm ERR! Test failed.  See above for more details.
```

**Comment by mrsteele** [comment]
So an assertion error normally tells me that the test if failing because an expectation that you have made is not met.

Would you mind adding what `mockStore` looks like, as well as what `cExpect` and `expectedActions` have in them at this point in your code?

**Comment by matthewfbenjamin** [comment]
mockStore:
```
const store = mockStore({
        isSending: false,
        authors: {},
        ui: { error: '' },
      })
```

`cExpect = chai.expect`

expectedActions:
```const expectedActions = [
    { type: `${constants.NAME}/START_AUTHOR_FETCH` },
    {
      type: `${constants.NAME}/RETURN_AUTHOR_FETCH_SUCCESS`,
      authors: {},
    },
  ]
```

**Comment by mrsteele** [comment]
Is `mockStore` this: https://github.com/arnaudbenard/redux-mock-store?

**Comment by matthewfbenjamin** [comment]
yes, and it's setup like this:

```
const middlewares = [thunk]
const mockStore = configureMockStore(middlewares)
```
Do you think I need to set up a middleware to use this library?

**Comment by mrsteele** [comment]
You shouldn't this library simply uses `mitm` to intercept contentful requests and returns your stubbed data. Let me look at this a bit more...

**Comment by matthewfbenjamin** [comment]
@mrsteele thank you for your help! I really appreciate it

**Comment by mrsteele** [comment]
comment out this line and let me know what happens:
```
          cExpect(response[0]).to.deep.equal(expectedActions[0])
```

**Comment by matthewfbenjamin** [comment]
I get the same error.

**Comment by mrsteele** [comment]
really stupid request, but what about:
```
  describe('fetchAuthors()', () => {
    // Contentfaux.unstub()
    it('should kick off two actions', () => {
      const store = mockStore({
        isSending: false,
        authors: {},
        ui: { error: '' },
      })
      return store.dispatch({type: 'TEST'})
    })
  })
```

**Comment by matthewfbenjamin** [comment]
Interestingly, I got the log lines from contentfaux `Unstubbing Contentful...` and `stubbing Contentful...` which I wasn't getting before, but then after that, I get the assertion error.

![screen shot 2017-11-29 at 5 49 24 pm](https://user-images.githubusercontent.com/9419421/33403266-ae5265f8-d52d-11e7-84ad-2461d2c8959e.png)

**Comment by mrsteele** [comment]
So I'm a little unfamiliar with the `mockStore` api, but you might want to something like this:
```js
describe('fetchAuthors()', () => {
    // Contentfaux.unstub()
    it('should kick off two actions', (done) => {
      const store = mockStore({
        isSending: false,
        authors: {},
        ui: { error: '' },
      })
      store.dispatch(actions.fetchAuthors())
        .then(() => {
          const response = store.getActions()
          cExpect(response).to.have.lengthOf(2)
          cExpect(response[0]).to.deep.equal(expectedActions[0])
          done()
        }).catch(done)
    })
  })
```

**Comment by matthewfbenjamin** [comment]
That didn't fix anything. I think it has to do with the `mitm.on` return of the `stub` function. Question, is there a specific folder where the json files have to be? right now the file strcture is

src
|
|--- Author > Author.test.js
|--- contentfaux > Array.json

**Comment by mrsteele** [comment]
Per your question: It should use your root directory to find the `./contentfaux` directory with your stubbed data.

I'll have to get back to you with the issue. I do know of only one bug with `contentfaux` that `mitm` actually intercepts ALL requests, instead of just Contentful requests, so we have that in are radars but probably wont get to it anytime soon.
